language: c++

matrix:
  include:
    - env: CONF="--enable-vlc"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons
    - env: CONF="--enable-vlc"
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-gst"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons
    - env: CONF="--enable-gst"
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-alsa --enable-jack --enable-vlc --enable-gst"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-alsa --enable-jack --enable-vlc --enable-gst"
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install automake || true
    brew install zeromq || true
    fi

script:
  - |
    ./bootstrap
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
    export CC=gcc-9
    export CXX=g++-9
    fi
    ./configure $CONF
    make

